import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  // GLP-1/GIP
  { name: "Tirzepatide 10mg/3ml", slug: "tirzepatide-10mg-3ml", category: "GLP-1", dosage: "10mg", volume: "3ml", retailPrice: 680, wholesalePrice: 410 },
  { name: "Tirzepatide 20mg/3ml", slug: "tirzepatide-20mg-3ml", category: "GLP-1", dosage: "20mg", volume: "3ml", retailPrice: 910, wholesalePrice: 550 },
  { name: "Tirzepatide 30mg/3ml", slug: "tirzepatide-30mg-3ml", category: "GLP-1", dosage: "30mg", volume: "3ml", retailPrice: 1250, wholesalePrice: 750 },
  { name: "Tirzepatide 40mg/3ml", slug: "tirzepatide-40mg-3ml", category: "GLP-1", dosage: "40mg", volume: "3ml", retailPrice: 1470, wholesalePrice: 880 },
  { name: "Tirzepatide 40mg", slug: "tirzepatide-40mg", category: "GLP-1", dosage: "40mg", retailPrice: 1710, wholesalePrice: 1030 },
  { name: "Tirzepatide 50mg/3ml", slug: "tirzepatide-50mg-3ml", category: "GLP-1", dosage: "50mg", volume: "3ml", retailPrice: 1590, wholesalePrice: 950 },
  { name: "Tirzepatide 60mg/3ml", slug: "tirzepatide-60mg-3ml", category: "GLP-1", dosage: "60mg", volume: "3ml", retailPrice: 1780, wholesalePrice: 1070 },
  { name: "Retatrutide 10mg/3ml", slug: "retatrutide-10mg-3ml", category: "GLP-1", dosage: "10mg", volume: "3ml", retailPrice: 1170, wholesalePrice: 700 },
  { name: "Retatrutide 15mg", slug: "retatrutide-15mg", category: "GLP-1", dosage: "15mg", retailPrice: 1710, wholesalePrice: 1030 },
  { name: "Retatrutide 20mg/3ml", slug: "retatrutide-20mg-3ml", category: "GLP-1", dosage: "20mg", volume: "3ml", retailPrice: 1700, wholesalePrice: 1020 },
  { name: "Retatrutide 30mg/3ml", slug: "retatrutide-30mg-3ml", category: "GLP-1", dosage: "30mg", volume: "3ml", retailPrice: 2150, wholesalePrice: 1290 },
  { name: "Retatrutide 30mg", slug: "retatrutide-30mg", category: "GLP-1", dosage: "30mg", retailPrice: 2510, wholesalePrice: 1510 },
  { name: "Retatrutide 40mg/3ml", slug: "retatrutide-40mg-3ml", category: "GLP-1", dosage: "40mg", volume: "3ml", retailPrice: 2460, wholesalePrice: 1480 },
  { name: "Semaglutide 30mg/3ml", slug: "semaglutide-30mg-3ml", category: "GLP-1", dosage: "30mg", volume: "3ml", retailPrice: 920, wholesalePrice: 550 },
  { name: "Semaglutide 30mg", slug: "semaglutide-30mg", category: "GLP-1", dosage: "30mg", retailPrice: 1270, wholesalePrice: 760 },

  // Outros peptídeos
  { name: "Cargrilintide 10mg", slug: "cargrilintide-10mg", retailPrice: 1580, wholesalePrice: 950 },
  { name: "Adipotide 5mg", slug: "adipotide-5mg", retailPrice: 1010, wholesalePrice: 610 },
  { name: "Survodutide 10mg", slug: "survodutide-10mg", retailPrice: 1990, wholesalePrice: 1190 },
  { name: "NAD+ 1000mg", slug: "nad-1000mg", retailPrice: 1010, wholesalePrice: 610 },
  { name: "Epithalon 50mg", slug: "epithalon-50mg", retailPrice: 1010, wholesalePrice: 610 },
  { name: "TB500 10mg", slug: "tb500-10mg", retailPrice: 1010, wholesalePrice: 610, imageUrl: "/imagensProdutos/tb500-rotulobranco.png" },
  { name: "BPC157 10mg", slug: "bpc157-10mg", retailPrice: 600, wholesalePrice: 360, imageUrl: "/imagensProdutos/bpc157.png" },
  { name: "CJC-1295 without DAC 10mg", slug: "cjc1295-without-dac-10mg", retailPrice: 1010, wholesalePrice: 610, imageUrl: "/imagensProdutos/cjc1295-rotulobranco.png" },
  { name: "CJC-1295 with DAC 5mg", slug: "cjc1295-with-dac-5mg", retailPrice: 1010, wholesalePrice: 610, imageUrl: "/imagensProdutos/cjc1295-rotulobranco.png" },
  { name: "Melanotan-1 10mg", slug: "melanotan-1-10mg", retailPrice: 450, wholesalePrice: 270, imageUrl: "/imagensProdutos/melanotan-1.png" },
  { name: "Melanotan-2 10mg", slug: "melanotan-2-10mg", retailPrice: 450, wholesalePrice: 270, imageUrl: "/imagensProdutos/melanotan-2.png" },
  { name: "GHK-CU 100mg", slug: "ghk-cu-100mg", retailPrice: 540, wholesalePrice: 320, imageUrl: "/imagensProdutos/ghk-cu-rotulobranco.png" },
  { name: "Most-c 40mg", slug: "most-c-40mg", retailPrice: 1230, wholesalePrice: 740, imageUrl: "/imagensProdutos/mots-c.png" },
  { name: "SS-31 50mg", slug: "ss-31-50mg", retailPrice: 2460, wholesalePrice: 1480, imageUrl: "/imagensProdutos/SS31.png" },
  { name: "IGF-1LR3 1mg", slug: "igf-1lr3-1mg", retailPrice: 1360, wholesalePrice: 820, imageUrl: "/imagensProdutos/igf-1LR3.png" },
  { name: "IGF-DES 2mg", slug: "igf-des-2mg", retailPrice: 480, wholesalePrice: 290, imageUrl: "/imagensProdutos/igf-des.png" },
  { name: "DSIP 10mg", slug: "dsip-10mg", retailPrice: 540, wholesalePrice: 320 },

  // Segunda tabela
  { name: "LL-37 5mg", slug: "ll-37-5mg", retailPrice: 730, wholesalePrice: 440 },
  { name: "AICAR 50mg", slug: "aicar-50mg", retailPrice: 600, wholesalePrice: 360 },
  { name: "PT141 10mg", slug: "pt141-10mg", retailPrice: 480, wholesalePrice: 290 },
  { name: "Oxytocin acetate 10mg", slug: "oxytocin-acetate-10mg", retailPrice: 670, wholesalePrice: 400 },
  { name: "Kisspeptin-10 10mg", slug: "kisspeptin-10-10mg", retailPrice: 670, wholesalePrice: 400 },
  { name: "ARA-290 10mg", slug: "ara-290-10mg", retailPrice: 540, wholesalePrice: 320 },
  { name: "Hexarelin Acetate 5mg", slug: "hexarelin-acetate-5mg", retailPrice: 670, wholesalePrice: 400 },
  { name: "Humanin 10mg", slug: "humanin-10mg", retailPrice: 1300, wholesalePrice: 780 },
  { name: "HGH Fragment 176-191 5mg", slug: "hgh-fragment-176-191-5mg", retailPrice: 470, wholesalePrice: 320 },
  { name: "Tesamorelin 10mg", slug: "tesamorelin-10mg", retailPrice: 1080, wholesalePrice: 650 },
  { name: "Ipamorelin 10mg", slug: "ipamorelin-10mg", retailPrice: 600, wholesalePrice: 360 },
  { name: "Semax 10mg", slug: "semax-10mg", retailPrice: 670, wholesalePrice: 400 },
  { name: "Thymalin 100mg", slug: "thymalin-100mg", retailPrice: 1680, wholesalePrice: 1010 },
  { name: "Mazdutite 10mg", slug: "mazdutite-10mg", retailPrice: 1230, wholesalePrice: 740 },
  { name: "Lipo-c 5mg", slug: "lipo-c-5mg", retailPrice: 640, wholesalePrice: 380 },
  { name: "Sermorelin Acetate 10mg", slug: "sermorelin-acetate-10mg", retailPrice: 950, wholesalePrice: 570 },
  { name: "AOD-9604 10mg", slug: "aod-9604-10mg", retailPrice: 980, wholesalePrice: 590 },
  { name: "HCG 5000iu", slug: "hcg-5000iu", retailPrice: 730, wholesalePrice: 440 },
  { name: "Selank 10mg", slug: "selank-10mg", retailPrice: 670, wholesalePrice: 400 },
  { name: "PEG MGF 2mg", slug: "peg-mgf-2mg", retailPrice: 760, wholesalePrice: 460 },
  { name: "MGF 2mg", slug: "mgf-2mg", retailPrice: 380, wholesalePrice: 230 },
  { name: "Melatonin 10mg", slug: "melatonin-10mg", retailPrice: 510, wholesalePrice: 310 },
  { name: "GHRP-2 Acetate 10mg", slug: "ghrp-2-acetate-10mg", retailPrice: 480, wholesalePrice: 290 },
  { name: "GHRP-6 Acetate 10mg", slug: "ghrp-6-acetate-10mg", retailPrice: 480, wholesalePrice: 290 },
  { name: "Snap-8 5mg", slug: "snap-8-5mg", retailPrice: 480, wholesalePrice: 290 },
  { name: "ACE-031 1mg", slug: "ace-031-1mg", retailPrice: 1860, wholesalePrice: 1120 },
  { name: "BPC157 10mg + GHK-CU 50mg + TB500 10mg", slug: "bpc157-10mg-ghkcu-50mg-tb500-10mg", retailPrice: 1360, wholesalePrice: 820, imageUrl: "/imagensProdutos/ghk-cu-rotulobranco.png" },
  { name: "Glutathione 1500mg", slug: "glutathione-1500mg", retailPrice: 830, wholesalePrice: 500 },
  { name: "BPC157 10mg + TB500 10mg", slug: "bpc157-10mg-tb500-10mg", retailPrice: 1220, wholesalePrice: 730, imageUrl: "/imagensProdutos/bpc157.png" },
  { name: "CJC-1295DAC 5mg + IPA 5mg", slug: "cjc1295dac-5mg-ipa-5mg", retailPrice: 790, wholesalePrice: 470, imageUrl: "/imagensProdutos/cjc1295-rotulobranco.png" },
  { name: "5-amino-1mq 30mg/3ml", slug: "5-amino-1mq-30mg-3ml", retailPrice: 750, wholesalePrice: 530 },
  { name: "Botulinum toxin 100iu", slug: "botulinum-toxin-100iu", retailPrice: 1150, wholesalePrice: 690 },
  { name: "HMG 75iu", slug: "hmg-75iu", retailPrice: 700, wholesalePrice: 420 },
  { name: "Pnc-27 10mg", slug: "pnc-27-10mg", retailPrice: 890, wholesalePrice: 530 },

  // Terceira tabela
  { name: "Follistatin-344 5mg", slug: "follistatin-344-5mg", retailPrice: 760, wholesalePrice: 460 },
  { name: "KissPeptin-10 10mg", slug: "kisspeptin-10-10mg-alt", retailPrice: 1330, wholesalePrice: 800 },
  { name: "KPV 10mg", slug: "kpv-10mg", retailPrice: 730, wholesalePrice: 440 },
  { name: "VIP 10mg", slug: "vip-10mg", retailPrice: 1200, wholesalePrice: 720 },
  { name: "Dermorphin 10mg", slug: "dermorphin-10mg", retailPrice: 450, wholesalePrice: 270 },
  { name: "Lemon bottle 10mg", slug: "lemon-bottle-10mg", retailPrice: 600, wholesalePrice: 360 },
  { name: "Klow 80mg", slug: "klow-80mg", retailPrice: 1520, wholesalePrice: 910 },
  { name: "Cardiogen 20mg", slug: "cardiogen-20mg", retailPrice: 670, wholesalePrice: 400 },
  { name: "Cerebrolysin 60mg", slug: "cerebrolysin-60mg", retailPrice: 540, wholesalePrice: 320 },
  { name: "PP-405 30ml", slug: "pp-405-30ml", retailPrice: 830, wholesalePrice: 500 },
  { name: "Thymosin-Alpha 1 10mg", slug: "thymosin-alpha-1-10mg", retailPrice: 980, wholesalePrice: 590 },
  { name: "Pinealon 10mg", slug: "pinealon-10mg", retailPrice: 540, wholesalePrice: 320 },
  { name: "SLU-PP-332 30mg/3ml", slug: "slu-pp-332-30mg-3ml", retailPrice: 750, wholesalePrice: 530 },
  { name: "SLU-PP-332 caps 3mg/60caps", slug: "slu-pp-332-caps-3mg-60caps", retailPrice: 750, wholesalePrice: 530 },
  { name: "5-amino-1mq 30mg/3ml (dup)", slug: "5-amino-1mq-30mg-3ml-dup", retailPrice: 750, wholesalePrice: 530, status: "archived" },
  { name: "Dihexa", slug: "dihexa-breve", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "BAM15", slug: "bam15-breve", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Fox-04-dri", slug: "fox-04-dri-breve", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Gonadorelin", slug: "gonadorelin-breve", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Dermorphin (Breve)", slug: "dermorphin-breve", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Clean Firestarter (Mots-c + SS31 + SLU) 60mg/3ml", slug: "clean-firestarter-60mg-3ml", retailPrice: 1500, wholesalePrice: 1050 },
  { name: "Clean SuperSlim 20mg/3ml (Reta + Tirze)", slug: "clean-superslim-20mg-3ml", retailPrice: 1800, wholesalePrice: 1080 },
  { name: "Clean SuperSlim 40mg/3ml (Reta + Tirze)", slug: "clean-superslim-40mg-3ml", retailPrice: 2500, wholesalePrice: 1500 },
  { name: "Clean SuperSlim 60mg/3ml (Reta + Tirze)", slug: "clean-superslim-60mg-3ml", retailPrice: 3200, wholesalePrice: 1920 },
  { name: "Clean SuperSlim+ 23mg/3ml (Reta + Tirze + Cagri)", slug: "clean-superslim-plus-23mg-3ml", retailPrice: 2200, wholesalePrice: 1320 },
  { name: "Clean SuperSlim+ 43mg/3ml (Reta + Tirze + Cagri)", slug: "clean-superslim-plus-43mg-3ml", retailPrice: 2800, wholesalePrice: 1680 },
  { name: "Clean SweetDreams (Disp + Epithalon + Selank)", slug: "clean-sweetdreams", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Clean SweetDreams+ (Disp + Epithalon + Dermorphin)", slug: "clean-sweetdreams-plus", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Clean SuperFocus (Dihexa + Semax + Cerebrolysin)", slug: "clean-superfocus", retailPrice: 0, wholesalePrice: 0, status: "soon" },
  { name: "Caneta 3ml", slug: "caneta-3ml", volume: "3ml", retailPrice: 300, wholesalePrice: 300 },
];

const slugImages: Record<string, string> = {
  "5-amino-1mq-30mg-3ml": "/imagensProdutos/5-Amino-1MQ.jpg",
  "5-amino-1mq-30mg-3ml-dup": "/imagensProdutos/5-Amino-1MQ.jpg",
  "ace-031-1mg": "/imagensProdutos/ACE-031.jpg",
  "adipotide-5mg": "/imagensProdutos/adipotide.jpg",
  "aicar-50mg": "/imagensProdutos/AICAR.jpg",
  "aod-9604-10mg": "/imagensProdutos/AOD-9604.jpg",
  "ara-290-10mg": "/imagensProdutos/ARA-290.jpg",
  "bam15-breve": "/imagensProdutos/BAM15.jpg",
  "botulinum-toxin-100iu": "/imagensProdutos/Botulinum Toxin.jpg",
  "cardiogen-20mg": "/imagensProdutos/Cardiogen.jpg",
  "cerebrolysin-60mg": "/imagensProdutos/Cerebrolysin.jpg",
  "cargrilintide-10mg": "/imagensProdutos/Cargrilintide.jpg",
  "dihexa-breve": "/imagensProdutos/Dihexa.jpg",
  "dermorphin-10mg": "/imagensProdutos/demorphin.jpg",
  "dermorphin-breve": "/imagensProdutos/demorphin.jpg",
  "dsip-10mg": "/imagensProdutos/dsip.jpg",
  "epithalon-50mg": "/imagensProdutos/epithalon.jpg",
  "fox-04-dri-breve": "/imagensProdutos/Fox-04-dri.jpg",
  "follistatin-344-5mg": "/imagensProdutos/Follistatin-344.jpg",
  "ghrp-2-acetate-10mg": "/imagensProdutos/GHRP-2 Acetate.jpg",
  "ghrp-6-acetate-10mg": "/imagensProdutos/GHRP-6 Acetate.jpg",
  "glutathione-1500mg": "/imagensProdutos/Glutathione.jpg",
  "gonadorelin-breve": "/imagensProdutos/Gonadorelin.jpg",
  "hcg-5000iu": "/imagensProdutos/hcg.jpg",
  "hexarelin-acetate-5mg": "/imagensProdutos/Hexarelin Acetate.jpg",
  "hgh-fragment-176-191-5mg": "/imagensProdutos/HGH Fragment 176-191.jpg",
  "hmg-75iu": "/imagensProdutos/hmg.jpg",
  "humanin-10mg": "/imagensProdutos/Humanin.jpg",
  "ll-37-5mg": "/imagensProdutos/LL-37.jpg",
  "ipamorelin-10mg": "/imagensProdutos/Ipamorelin.jpg",
  "kisspeptin-10-10mg": "/imagensProdutos/Kisspeptin-10.jpg",
  "kisspeptin-10-10mg-alt": "/imagensProdutos/Kisspeptin-10.jpg",
  "klow-80mg": "/imagensProdutos/klow.jpg",
  "kpv-10mg": "/imagensProdutos/kpv.jpg",
  "lemon-bottle-10mg": "/imagensProdutos/lemon-bottle.jpg",
  "lipo-c-5mg": "/imagensProdutos/Lipo-C.jpg",
  "mazdutite-10mg": "/imagensProdutos/Mazdutite.jpg",
  "melatonin-10mg": "/imagensProdutos/Melatonin.jpg",
  "mgf-2mg": "/imagensProdutos/MGF.jpg",
  "melanotan-1-10mg": "/imagensProdutos/Melanotan-1.jpg",
  "melanotan-2-10mg": "/imagensProdutos/Melanotan-2.jpg",
  "most-c-40mg": "/imagensProdutos/Most-c.jpg",
  "nad-1000mg": "/imagensProdutos/nad+.jpg",
  "oxytocin-acetate-10mg": "/imagensProdutos/Oxytocin Acetate.jpg",
  "peg-mgf-2mg": "/imagensProdutos/PEG-MGF.jpg",
  "pinealon-10mg": "/imagensProdutos/Pinealon.jpg",
  "pnc-27-10mg": "/imagensProdutos/pnc-27.jpg",
  "pp-405-30ml": "/imagensProdutos/PP-405.jpg",
  "pt141-10mg": "/imagensProdutos/PT-141.jpg",
  "selank-10mg": "/imagensProdutos/Selank.jpg",
  "semax-10mg": "/imagensProdutos/Semax.jpg",
  "sermorelin-acetate-10mg": "/imagensProdutos/Sermorelin Acetate.jpg",
  "slu-pp-332-30mg-3ml": "/imagensProdutos/SLU-PP-332.jpg",
  "slu-pp-332-caps-3mg-60caps": "/imagensProdutos/SLU-PP-332.jpg",
  "snap-8-5mg": "/imagensProdutos/Snap-8.jpg",
  "ss-31-50mg": "/imagensProdutos/SS31.png",
  "survodutide-10mg": "/imagensProdutos/survodutide.jpg",
  "semaglutide-30mg-3ml": "/imagensProdutos/semaglutide.jpg",
  "semaglutide-30mg": "/imagensProdutos/semaglutide.jpg",
  "retatrutide-10mg-3ml": "/imagensProdutos/retatrutide.jpg",
  "retatrutide-15mg": "/imagensProdutos/retatrutide.jpg",
  "retatrutide-20mg-3ml": "/imagensProdutos/retatrutide.jpg",
  "retatrutide-30mg-3ml": "/imagensProdutos/retatrutide.jpg",
  "retatrutide-30mg": "/imagensProdutos/retatrutide.jpg",
  "retatrutide-40mg-3ml": "/imagensProdutos/retatrutide.jpg",
  "tirzepatide-10mg-3ml": "/imagensProdutos/tizerpatide.jpg",
  "tirzepatide-20mg-3ml": "/imagensProdutos/tizerpatide.jpg",
  "tirzepatide-30mg-3ml": "/imagensProdutos/tizerpatide.jpg",
  "tirzepatide-40mg-3ml": "/imagensProdutos/tizerpatide.jpg",
  "tirzepatide-40mg": "/imagensProdutos/tizerpatide.jpg",
  "tirzepatide-50mg-3ml": "/imagensProdutos/tizerpatide.jpg",
  "tirzepatide-60mg-3ml": "/imagensProdutos/tizerpatide.jpg",
  "tesamorelin-10mg": "/imagensProdutos/Tesamorelin.jpg",
  "thymalin-100mg": "/imagensProdutos/Thymalin.jpg",
  "thymosin-alpha-1-10mg": "/imagensProdutos/Thymosin Alpha-1.jpg",
  "vip-10mg": "/imagensProdutos/vip.jpg",
  "caneta-3ml": "/imagensProdutos/Caneta3ml.jpg",
  "clean-firestarter-60mg-3ml": "/imagensProdutos/Clean Firestarter (Mots-c + SS31 + SLU) 60mg3ml.jpg",
  "clean-superfocus": "/imagensProdutos/Clean SuperFocus (Dihexa + Semax + Cerebrolysin).jpg",
  "clean-superslim-20mg-3ml": "/imagensProdutos/Clean SuperSlim 20mg3ml (Reta + Tirze).jpg",
  "clean-superslim-40mg-3ml": "/imagensProdutos/Clean SuperSlim 40mg3ml (Reta + Tirze).jpg",
  "clean-superslim-60mg-3ml": "/imagensProdutos/Clean SuperSlim 60mg3ml (Reta + Tirze).jpg",
  "clean-superslim-plus-23mg-3ml": "/imagensProdutos/Clean SuperSlim+ 23mg3ml (Reta + Tirze + Cagri).jpg",
  "clean-superslim-plus-43mg-3ml": "/imagensProdutos/Clean SuperSlim+ 43mg3ml (Reta + Tirze + Cagri).jpg",
  "clean-sweetdreams": "/imagensProdutos/Clean SweetDreams (Disp + Epithalon + Selank).jpg",
  "clean-sweetdreams-plus": "/imagensProdutos/Clean SweetDreams+ (Disp + Epithalon + Dermorphin).jpg",
};

const fallbackImages = [
  "/carrossel/Gemini_Generated_Image_dj1l4udj1l4udj1l.png",
  "/carrossel/Gemini_Generated_Image_oif6u6oif6u6oif6.png",
  "/carrossel/Gemini_Generated_Image_yi00vsyi00vsyi00.png",
];

async function main() {
  const productsWithImages = products.map((product, idx) => ({
    ...product,
    imageUrl:
      product.imageUrl ??
      slugImages[product.slug] ??
      fallbackImages[idx % fallbackImages.length],
  }));

  for (const product of productsWithImages) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
